"""Faithful transcription of Letters and Sounds (2007), DFES-00281-2007.

Crown copyright 2007. Open Government Licence v3.0.
Source PDF: https://assets.publishing.service.gov.uk/media/5a7aa7b6e5274a34770e630c/Letters_and_Sounds_-_DFES-00281-2007.pdf

Page numbers below are the *printed* page numbers in that PDF.
"""

# --------------------------------------------------------------------------
# GPC inventory.  order = the global teaching index used to build a ceiling.
# --------------------------------------------------------------------------
# (id, grapheme, order, phase, set, ipa, spoken_label, stretchable, kind,
#  examples, source, extra)

GPCS = [
    # ---- Phase 2, set 1 (p.50, p.69) ----
    ("s", "s", 1, 2, 1, "s", "sss", True, "single", ["sat", "sit", "us"], "ls2007:p.50", {}),
    ("a", "a", 2, 2, 1, "a", "aaa", True, "single", ["at", "sat", "pat"], "ls2007:p.50", {}),
    ("t", "t", 3, 2, 1, "t", "t", False, "single", ["tap", "sat", "it"], "ls2007:p.50", {}),
    ("p", "p", 4, 2, 1, "p", "p", False, "single", ["pat", "tap", "pip"], "ls2007:p.50", {}),
    (
        "s_z", "s", 1, 2, 1, "z", "zzz", True, "single", ["as", "is", "has", "his"],
        "ls2007:p.69 (footnote **)",
        {
            "variant_of": "s",
            "note": (
                "L&S footnote, p.69: 'The sounds represented by f in of, and by s in as, "
                "is, has and his should also not cause problems at this stage'."
            ),
        },
    ),
    # ---- Phase 2, set 2 ----
    ("i", "i", 5, 2, 2, "ɪ", "iii", True, "single", ["it", "in", "sit"], "ls2007:p.50", {}),
    ("n", "n", 6, 2, 2, "n", "nnn", True, "single", ["nip", "in", "pan"], "ls2007:p.50", {}),
    ("m", "m", 7, 2, 2, "m", "mmm", True, "single", ["mat", "man", "am"], "ls2007:p.50", {}),
    ("d", "d", 8, 2, 2, "d", "d", False, "single", ["dad", "did", "dip"], "ls2007:p.50", {}),
    # ---- Phase 2, set 3 ----
    ("g", "g", 9, 2, 3, "ɡ", "g", False, "single", ["tag", "gap", "dig"], "ls2007:p.50", {}),
    ("o", "o", 10, 2, 3, "ɒ", "o", True, "single", ["on", "got", "top"], "ls2007:p.50", {}),
    ("c", "c", 11, 2, 3, "k", "c", False, "single", ["can", "cat", "cot"], "ls2007:p.50", {}),
    ("k", "k", 12, 2, 3, "k", "k", False, "single", ["kid", "kit"], "ls2007:p.50", {}),
    # ---- Phase 2, set 4 ----
    (
        "ck", "ck", 13, 2, 4, "k", "k", False, "digraph", ["kick", "sock", "back"],
        "ls2007:p.50, p.69",
        {
            "note": (
                "L&S p.69: 'Teach that ck together stands for the same sound as c and k "
                "separately - ck never comes at the beginning of a word, but often comes "
                "at the end or near the end.'"
            )
        },
    ),
    ("e", "e", 14, 2, 4, "e", "e", True, "single", ["get", "pen", "ten"], "ls2007:p.50", {}),
    ("u", "u", 15, 2, 4, "ʌ", "u", True, "single", ["up", "mum", "run"], "ls2007:p.50", {}),
    ("r", "r", 16, 2, 4, "ɹ", "rrr", True, "single", ["rim", "rat", "rug"], "ls2007:p.50", {}),
    # ---- Phase 2, set 5 ----
    ("h", "h", 17, 2, 5, "h", "h", False, "single", ["had", "him", "hot"], "ls2007:p.50", {}),
    ("b", "b", 18, 2, 5, "b", "b", False, "single", ["but", "big", "bed"], "ls2007:p.50", {}),
    ("f", "f", 19, 2, 5, "f", "fff", True, "single", ["fit", "fun", "fog"], "ls2007:p.50", {}),
    (
        "f_v", "f", 19, 2, 5, "v", "vvv", True, "single", ["of"],
        "ls2007:p.69 (footnote **)",
        {
            "variant_of": "f",
            "note": "L&S footnote, p.69: the f in 'of' stands for /v/ and 'should not cause problems'.",
        },
    ),
    (
        "ff", "ff", 20, 2, 5, "f", "fff", True, "doubled", ["off", "puff", "huff"],
        "ls2007:p.50, p.70",
        {
            "note": (
                "L&S p.70: 'When the letters l, s and f double at the ends of some words "
                "and c is joined by k, it is a good idea to draw a line underneath both "
                "letters to show that they represent one phoneme (e.g. hill, pick)'."
            )
        },
    ),
    ("l", "l", 21, 2, 5, "l", "lll", True, "single", ["lap", "let", "leg"], "ls2007:p.50", {}),
    ("ll", "ll", 22, 2, 5, "l", "lll", True, "doubled", ["bell", "fill", "doll"], "ls2007:p.50, p.70", {}),
    ("ss", "ss", 23, 2, 5, "s", "sss", True, "doubled", ["less", "hiss", "kiss"], "ls2007:p.50, p.70", {}),
    # ---- Phase 3, set 6 ----
    ("j", "j", 24, 3, 6, "dʒ", "j", False, "single", ["jam", "jet", "jog"], "ls2007:p.76", {}),
    ("v", "v", 25, 3, 6, "v", "vvv", True, "single", ["van", "vet", "visit"], "ls2007:p.76", {}),
    ("w", "w", 26, 3, 6, "w", "w", False, "single", ["will", "win", "web"], "ls2007:p.76", {}),
    ("x", "x", 27, 3, 6, "ks", "ks", False, "single", ["mix", "box", "six"], "ls2007:p.76", {}),
    # ---- Phase 3, set 7 ----
    ("y", "y", 28, 3, 7, "j", "y", False, "single", ["yes", "yet", "yell"], "ls2007:p.76", {}),
    ("z", "z", 29, 3, 7, "z", "zzz", True, "single", ["zip", "zigzag"], "ls2007:p.76", {}),
    ("zz", "zz", 30, 3, 7, "z", "zzz", True, "doubled", ["buzz", "jazz"], "ls2007:p.76", {}),
    ("qu", "qu", 31, 3, 7, "kw", "kw", False, "digraph", ["quiz", "quit", "quack"], "ls2007:p.76", {}),
    # ---- Phase 3, consonant digraphs ----
    ("ch", "ch", 32, 3, None, "tʃ", "ch", False, "digraph", ["chop", "chin", "much"], "ls2007:p.76, p.101", {}),
    ("sh", "sh", 33, 3, None, "ʃ", "shh", True, "digraph", ["ship", "shop", "fish"], "ls2007:p.76, p.101", {}),
    ("th", "th", 34, 3, None, "θ", "th (unvoiced, as in thin)", True, "digraph",
     ["thin", "thick", "with"], "ls2007:p.76, p.101", {}),
    ("th_voiced", "th", 34, 3, None, "ð", "th (voiced, as in them)", True, "digraph",
     ["them", "then", "that", "this"], "ls2007:p.101",
     {"variant_of": "th",
      "note": "L&S lists both pronunciations in one 'th' column (p.101); they are taught together."}),
    ("ng", "ng", 35, 3, None, "ŋ", "ng", True, "digraph", ["ring", "song", "king"], "ls2007:p.76, p.101", {}),
    # ---- Phase 3, vowel graphemes ----
    ("ai", "ai", 36, 3, None, "eɪ", "ay", True, "digraph", ["rain", "wait", "sail"], "ls2007:p.76, p.102", {}),
    ("ee", "ee", 37, 3, None, "iː", "ee", True, "digraph", ["see", "week", "feet"], "ls2007:p.76, p.102", {}),
    ("igh", "igh", 38, 3, None, "aɪ", "igh (as in night)", True, "trigraph",
     ["high", "night", "light"], "ls2007:p.76, p.102", {}),
    ("oa", "oa", 39, 3, None, "əʊ", "oh", True, "digraph", ["coat", "goat", "road"], "ls2007:p.76, p.102", {}),
    ("oo_long", "oo", 40, 3, None, "uː", "oo (long, as in moon)", True, "digraph",
     ["moon", "boot", "too"], "ls2007:p.76, p.102", {"variant_of": "oo"}),
    ("oo_short", "oo", 41, 3, None, "ʊ", "oo (short, as in book)", True, "digraph",
     ["book", "look", "good"], "ls2007:p.76, p.102", {"variant_of": "oo"}),
    ("ar", "ar", 42, 3, None, "ɑː", "ar", True, "digraph", ["car", "park", "farm"], "ls2007:p.77, p.102", {}),
    ("or", "or", 43, 3, None, "ɔː", "or", True, "digraph", ["for", "fork", "born"], "ls2007:p.77, p.102", {}),
    ("ur", "ur", 44, 3, None, "ɜː", "ur", True, "digraph", ["fur", "turn", "burn"], "ls2007:p.77, p.102", {}),
    ("ow", "ow", 45, 3, None, "aʊ", "ow (as in cow)", True, "digraph", ["now", "down", "cow"],
     "ls2007:p.77, p.102", {}),
    ("oi", "oi", 46, 3, None, "ɔɪ", "oy", True, "digraph", ["oil", "coin", "join"], "ls2007:p.77, p.102", {}),
    ("ear", "ear", 47, 3, None, "ɪə", "ear", True, "trigraph", ["ear", "hear", "near"],
     "ls2007:p.77, p.102", {}),
    ("air", "air", 48, 3, None, "ɛə", "air", True, "trigraph", ["air", "hair", "pair"],
     "ls2007:p.77, p.102", {}),
    ("ure", "ure", 49, 3, None, "ʊə", "ure (as in sure)", True, "trigraph", ["sure", "pure", "cure"],
     "ls2007:p.77, p.102", {}),
    ("er", "er", 50, 3, None, "ə", "uh (as at the end of letter)", True, "digraph",
     ["letter", "hammer", "summer"], "ls2007:p.77, p.102", {}),
    # ---- Phase 5, new graphemes for reading (p.151) ----
    ("ay", "ay", 51, 5, None, "eɪ", "ay", True, "digraph", ["day", "play", "say"], "ls2007:p.151", {}),
    ("ou", "ou", 52, 5, None, "aʊ", "ow (as in out)", True, "digraph", ["out", "about", "sound"],
     "ls2007:p.151", {}),
    ("ie", "ie", 53, 5, None, "aɪ", "eye", True, "digraph", ["pie", "tie", "cried"], "ls2007:p.151", {}),
    ("ea", "ea", 54, 5, None, "iː", "ee", True, "digraph", ["sea", "seat", "meat"], "ls2007:p.151", {}),
    ("oy", "oy", 55, 5, None, "ɔɪ", "oy", True, "digraph", ["boy", "toy", "joy"], "ls2007:p.151", {}),
    ("ir", "ir", 56, 5, None, "ɜː", "ur", True, "digraph", ["girl", "bird", "shirt"], "ls2007:p.151", {}),
    ("ue_oo", "ue", 57, 5, None, "uː", "oo (as in blue)", True, "digraph", ["clue", "blue", "true"],
     "ls2007:p.151", {"variant_of": "ue"}),
    ("ue_yoo", "ue", 58, 5, None, "juː", "yoo (as in cue)", True, "digraph", ["cue", "due", "value"],
     "ls2007:p.151", {"variant_of": "ue"}),
    ("aw", "aw", 59, 5, None, "ɔː", "or", True, "digraph", ["saw", "paw", "lawn"], "ls2007:p.151", {}),
    ("wh", "wh", 60, 5, None, "w", "w", False, "digraph", ["when", "which", "wheel"], "ls2007:p.151", {}),
    ("ph", "ph", 61, 5, None, "f", "fff", True, "digraph", ["phonics", "dolphin", "elephant"],
     "ls2007:p.151", {}),
    ("ew_oo", "ew", 62, 5, None, "uː", "oo (as in blew)", True, "digraph", ["blew", "grew", "flew"],
     "ls2007:p.151", {"variant_of": "ew"}),
    ("ew_yoo", "ew", 63, 5, None, "juː", "yoo (as in stew)", True, "digraph", ["stew", "few", "new"],
     "ls2007:p.151", {"variant_of": "ew"}),
    ("oe", "oe", 64, 5, None, "əʊ", "oh", True, "digraph", ["toe", "hoe", "goes"], "ls2007:p.151", {}),
    ("au", "au", 65, 5, None, "ɔː", "or", True, "digraph", ["haul", "launch", "author"],
     "ls2007:p.151", {}),
    ("ey_ee", "ey", 66, 5, None, "iː", "ee", True, "digraph", ["money", "honey", "donkey"],
     "ls2007:p.151", {"variant_of": "ey"}),
    # ---- Phase 5, split digraphs (p.152) ----
    ("a-e", "a-e", 67, 5, None, "eɪ", "ay", True, "split_digraph", ["came", "make", "game"],
     "ls2007:p.152", {"split": True}),
    ("e-e", "e-e", 68, 5, None, "iː", "ee", True, "split_digraph", ["these", "even", "theme"],
     "ls2007:p.152", {"split": True}),
    ("i-e", "i-e", 69, 5, None, "aɪ", "eye", True, "split_digraph", ["like", "time", "shine"],
     "ls2007:p.152", {"split": True}),
    ("o-e", "o-e", 70, 5, None, "əʊ", "oh", True, "split_digraph", ["bone", "home", "stone"],
     "ls2007:p.152", {"split": True}),
    ("u-e_oo", "u-e", 71, 5, None, "uː", "oo (as in rule)", True, "split_digraph",
     ["rule", "flute", "prune"], "ls2007:p.152", {"split": True, "variant_of": "u-e"}),
    ("u-e_yoo", "u-e", 72, 5, None, "juː", "yoo (as in cube)", True, "split_digraph",
     ["huge", "cube", "use"], "ls2007:p.152", {"split": True, "variant_of": "u-e"}),
    # ---- Phase 5, alternative pronunciations of known graphemes (p.153) ----
    ("a_ay", "a", 73, 5, None, "eɪ", "ay", True, "single", ["acorn", "bacon", "apron"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "a"}),
    ("a_ah", "a", 74, 5, None, "ɑː", "ar", True, "single", ["fast", "path", "bath"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "a",
                      "note": "L&S p.153: applies in the South of England only."}),
    ("a_o", "a", 75, 5, None, "ɒ", "o", True, "single", ["was", "what", "wash", "wasp"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "a"}),
    ("e_ee", "e", 76, 5, None, "iː", "ee", True, "single", ["he", "me", "she", "be"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "e"}),
    ("i_eye", "i", 77, 5, None, "aɪ", "eye", True, "single", ["mind", "find", "wild"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "i"}),
    ("o_oh", "o", 78, 5, None, "əʊ", "oh", True, "single", ["no", "so", "go", "old"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "o"}),
    ("u_yoo", "u", 79, 5, None, "juː", "yoo", True, "single", ["unit", "union", "music"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "u"}),
    ("u_oo", "u", 80, 5, None, "ʊ", "oo (short)", True, "single", ["put", "pull", "full", "push"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "u",
                      "note": "L&S p.153: applies in the South of England only."}),
    ("ow_oh", "ow", 81, 5, None, "əʊ", "oh", True, "digraph", ["low", "grow", "snow"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "ow"}),
    ("ie_ee", "ie", 82, 5, None, "iː", "ee", True, "digraph", ["chief", "field", "thief"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "ie"}),
    ("ea_e", "ea", 83, 5, None, "e", "e", True, "digraph", ["head", "bread", "deaf"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "ea"}),
    ("er_ur", "er", 84, 5, None, "ɜː", "ur", True, "digraph", ["her", "fern", "stern"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "er"}),
    ("ou_oo", "ou", 85, 5, None, "uː", "oo (long)", True, "digraph", ["you", "soup", "group"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "ou"}),
    ("ou_uu", "ou", 86, 5, None, "ʊ", "oo (short)", True, "digraph", ["could", "would", "should"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "ou"}),
    ("ou_oh", "ou", 87, 5, None, "əʊ", "oh", True, "digraph", ["mould", "shoulder", "boulder"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "ou"}),
    ("y_eye", "y", 88, 5, None, "aɪ", "eye", True, "single", ["by", "my", "try", "sky"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "y"}),
    ("y_i", "y", 89, 5, None, "ɪ", "iii", True, "single", ["gym", "crystal", "pyramid"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "y"}),
    ("y_ee", "y", 90, 5, None, "iː", "ee", True, "single", ["very", "happy", "funny"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "y"}),
    ("ch_k", "ch", 91, 5, None, "k", "k", False, "digraph", ["school", "christmas", "chemist"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "ch"}),
    ("ch_sh", "ch", 92, 5, None, "ʃ", "shh", True, "digraph", ["chef", "machine", "brochure"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "ch"}),
    ("c_s", "c", 93, 5, None, "s", "sss", True, "single", ["cell", "central", "cycle"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "c"}),
    ("g_j", "g", 94, 5, None, "dʒ", "j", False, "single", ["gent", "gem", "ginger"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "g"}),
    ("ey_ay", "ey", 95, 5, None, "eɪ", "ay", True, "digraph", ["they", "grey", "obey"],
     "ls2007:p.153", {"alternative_pronunciation": True, "variant_of": "ey"}),
    # ---- Phase 5, alternative spellings for reading (p.154) ----
    ("tch", "tch", 96, 5, None, "tʃ", "ch", False, "trigraph", ["catch", "fetch", "match"],
     "ls2007:p.154", {}),
    ("ture", "ture", 97, 5, None, "tʃə", "cher", True, "quadgraph", ["picture", "nature", "future"],
     "ls2007:p.154", {}),
    ("dge", "dge", 98, 5, None, "dʒ", "j", False, "trigraph", ["fudge", "hedge", "bridge"],
     "ls2007:p.154", {}),
    ("mb", "mb", 99, 5, None, "m", "mmm", True, "digraph", ["lamb", "climb", "thumb"],
     "ls2007:p.154", {}),
    ("gn", "gn", 100, 5, None, "n", "nnn", True, "digraph", ["gnat", "gnaw", "gnome"],
     "ls2007:p.154", {}),
    ("kn", "kn", 101, 5, None, "n", "nnn", True, "digraph", ["knit", "knee", "knock"],
     "ls2007:p.154", {}),
    ("wr", "wr", 102, 5, None, "ɹ", "rrr", True, "digraph", ["wrap", "wren", "write"],
     "ls2007:p.154", {}),
    # ---- kidnix additions (marked; see sources.toml) ----
    ("or_er", "or", 103, 5, None, "ɜː", "ur", True, "digraph", ["word", "worm", "work"],
     "kidnix",
     {"alternative_pronunciation": True, "variant_of": "or", "added_by": "kidnix",
      "note": (
          "Not in the L&S alternative-pronunciation table. Added because the DfE Reading "
          "Framework's Appendix 7 turns on it: a child taught 'or' as /or/ can read 'worn' "
          "but not 'worms'. Without this GPC the acceptance test cannot distinguish them."
      )}),
]

# Doubled consonants that L&S never introduces as GPCs but uses freely in its own
# word banks from set 4 onward (rocket -> no, carrot -> rr, rabbit -> bb, sitting -> tt).
# Added by kidnix at order 16 (end of Phase 2 set 4), which is where they first
# appear in the L&S banks.
KIDNIX_DOUBLETS = [
    ("bb", "b", ["rabbit", "rubbish"]),
    ("dd", "d", ["ladder", "sudden"]),
    ("gg", "g", ["digging", "wiggle"]),
    ("mm", "m", ["hammer", "summer"]),
    ("nn", "n", ["dinner", "banner"]),
    ("pp", "p", ["supper", "dropping"]),
    ("rr", "r", ["carrot", "sorry"]),
    ("tt", "t", ["letter", "better"]),
]

# Pseudo-GPCs used only to *reject* words.  They are never in any ceiling, at any
# phase; they exist so the lexicon can say precisely why a word is not decodable.
UNTAUGHT = [
    ("e_silent", "e", "silent final e (the second half of a split digraph, or a lone marker)",
     ["giraffe", "leaves", "have"]),
    ("le", "le", "final consonant-le syllable", ["puddle", "little", "table"]),
    ("ed_t", "ed", "-ed suffix pronounced /t/", ["jumped", "kicked", "asked"]),
    ("ed_d", "ed", "-ed suffix pronounced /d/", ["called", "filled"]),
    ("ei", "ei", "the 'ei' of their/vein", ["their", "vein"]),
    ("ere_er", "ere", "the 'ere' of were", ["were"]),
    ("oe_u", "oe", "the 'oe' of does", ["does"]),
    ("a_or", "a", "'a' after w pronounced /ɔː/", ["water", "warm", "war"]),
    ("o_u", "o", "'o' pronounced /ʌ/", ["some", "come", "one", "money"]),
    ("o_oo", "o", "'o' pronounced /uː/", ["into", "do", "who"]),
    ("augh", "augh", "the 'augh' of laughed/caught", ["laughed", "caught"]),
    ("ough", "ough", "the 'ough' family", ["thought", "through", "though"]),
    ("ai_e", "ai", "the 'ai' of said", ["said"]),
    ("eo", "eo", "the 'eo' of people", ["people"]),
    ("silent", "", "a letter that stands for no phoneme at all", ["friend", "island"]),
]

# --------------------------------------------------------------------------
# Word banks, transcribed column by column.
# key: (phase, ls_group, after_order, source, target_gpc or None)
# --------------------------------------------------------------------------

WORD_GROUPS = [
    # ---------------- Phase 2, p.69 ----------------
    dict(phase=2, ls_set=1, group="sets 1", after=4, source="ls2007:p.69", target=None,
         words=["at", "sat", "pat", "tap", "sap", "a", "as"]),
    dict(phase=2, ls_set=2, group="sets 1-2 (+i)", after=8, source="ls2007:p.69", target="i",
         words=["it", "is", "sit", "pit", "tip", "pip", "sip"]),
    dict(phase=2, ls_set=2, group="sets 1-2 (+n)", after=8, source="ls2007:p.69", target="n",
         words=["an", "in", "nip", "pan", "pin", "tin", "tan", "nap"]),
    dict(phase=2, ls_set=2, group="sets 1-2 (+m)", after=8, source="ls2007:p.69", target="m",
         words=["am", "man", "mam", "mat", "map", "pam", "tim", "sam"]),
    dict(phase=2, ls_set=2, group="sets 1-2 (+d)", after=8, source="ls2007:p.69", target="d",
         words=["dad", "sad", "dim", "dip", "din", "did", "sid", "and"]),
    dict(phase=2, ls_set=3, group="sets 1-3 (+g)", after=12, source="ls2007:p.69", target="g",
         words=["tag", "gag", "gig", "gap", "nag", "sag", "gas", "pig", "dig"]),
    dict(phase=2, ls_set=3, group="sets 1-3 (+o)", after=12, source="ls2007:p.69", target="o",
         words=["got", "on", "not", "pot", "top", "dog", "pop", "mog"]),
    dict(phase=2, ls_set=3, group="sets 1-3 (+c)", after=12, source="ls2007:p.69", target="c",
         words=["can", "cot", "cop", "cap", "cat", "cod"]),
    dict(phase=2, ls_set=3, group="sets 1-3 (+k)", after=12, source="ls2007:p.69", target="k",
         words=["kid", "kit", "kim", "ken"]),
    dict(phase=2, ls_set=4, group="sets 1-4 (+ck)", after=16, source="ls2007:p.69", target="ck",
         words=["kick", "sock", "sack", "dock", "pick", "sick", "pack", "ticket", "pocket"]),
    dict(phase=2, ls_set=4, group="sets 1-4 (+e)", after=16, source="ls2007:p.69", target="e",
         words=["get", "pet", "ten", "net", "pen", "peg", "met", "men", "neck"]),
    dict(phase=2, ls_set=4, group="sets 1-4 (+u)", after=16, source="ls2007:p.69", target="u",
         words=["up", "mum", "run", "mug", "cup", "sun", "tuck", "mud", "sunset"]),
    dict(phase=2, ls_set=4, group="sets 1-4 (+r)", after=16, source="ls2007:p.69", target="r",
         words=["rim", "rip", "ram", "rat", "rag", "rug", "rot", "rocket", "carrot"]),
    dict(phase=2, ls_set=5, group="sets 1-5 (+h)", after=23, source="ls2007:p.70", target="h",
         words=["had", "him", "his", "hot", "hut", "hop", "hum", "hit", "hat", "has", "hack", "hug"]),
    dict(phase=2, ls_set=5, group="sets 1-5 (+b)", after=23, source="ls2007:p.70", target="b",
         words=["but", "big", "back", "bet", "bad", "bag", "bed", "bud", "beg", "bug", "bun",
                "bus", "ben", "bat", "bit", "bucket", "beckon", "rabbit"]),
    dict(phase=2, ls_set=5, group="sets 1-5 (+f and ff)", after=23, source="ls2007:p.70", target="ff",
         words=["of", "if", "off", "fit", "fin", "fun", "fig", "fog", "puff", "huff", "cuff",
                "fan", "fat"]),
    dict(phase=2, ls_set=5, group="sets 1-5 (+l and ll)", after=23, source="ls2007:p.70", target="ll",
         words=["lap", "let", "leg", "lot", "lit", "bell", "fill", "doll", "tell", "sell",
                "bill", "nell", "dull", "laptop"]),
    dict(phase=2, ls_set=5, group="sets 1-5 (+ss)", after=23, source="ls2007:p.70", target="ss",
         words=["less", "hiss", "mass", "mess", "boss", "fuss", "pass", "kiss", "tess", "fusspot"]),
    # ---------------- Phase 3, p.100 ----------------
    dict(phase=3, ls_set=6, group="sets 1-6 (+j)", after=27, source="ls2007:p.100", target="j",
         words=["jam", "jill", "jet", "jog", "jack", "jen", "jet-lag", "jacket"]),
    dict(phase=3, ls_set=6, group="sets 1-6 (+v)", after=27, source="ls2007:p.100", target="v",
         words=["van", "vat", "vet", "vic", "ravi", "kevin", "visit", "velvet"]),
    dict(phase=3, ls_set=6, group="sets 1-6 (+w)", after=27, source="ls2007:p.100", target="w",
         words=["will", "win", "wag", "web", "wig", "wax", "cobweb", "wicked"]),
    dict(phase=3, ls_set=6, group="sets 1-6 (+x)", after=27, source="ls2007:p.100", target="x",
         words=["mix", "fix", "box", "tax", "six", "taxi", "vixen", "exit"]),
    dict(phase=3, ls_set=7, group="sets 1-7 (+y)", after=31, source="ls2007:p.100", target="y",
         words=["yap", "yes", "yet", "yell", "yum-yum"]),
    dict(phase=3, ls_set=7, group="sets 1-7 (+z/zz)", after=31, source="ls2007:p.100", target="zz",
         words=["zip", "zak", "buzz", "jazz", "zigzag"]),
    dict(phase=3, ls_set=7, group="sets 1-7 (+qu)", after=31, source="ls2007:p.100", target="qu",
         words=["quiz", "quit", "quick", "quack", "liquid"]),
    # ---------------- Phase 3, p.101 consonant digraphs ----------------
    dict(phase=3, ls_set=None, group="ch", after=32, source="ls2007:p.101", target="ch",
         words=["chop", "chin", "chug", "check", "such", "chip", "chill", "much", "rich", "chicken"]),
    dict(phase=3, ls_set=None, group="sh", after=33, source="ls2007:p.101", target="sh",
         words=["ship", "shop", "shed", "shell", "fish", "shock", "cash", "bash", "hush", "rush"]),
    dict(phase=3, ls_set=None, group="th", after=34, source="ls2007:p.101", target="th",
         words=["them", "then", "that", "this", "with", "moth", "thin", "thick", "path", "bath"]),
    dict(phase=3, ls_set=None, group="ng", after=35, source="ls2007:p.101", target="ng",
         words=["ring", "rang", "hang", "song", "wing", "rung", "king", "long", "sing", "ping-pong"]),
    # ---------------- Phase 3, p.102 vowel graphemes ----------------
    dict(phase=3, ls_set=None, group="ai", after=36, source="ls2007:p.102", target="ai",
         words=["wait", "gail", "hail", "pain", "aim", "sail", "main", "tail", "rain", "bait"]),
    dict(phase=3, ls_set=None, group="ee", after=37, source="ls2007:p.102", target="ee",
         words=["see", "feel", "weep", "feet", "jeep", "seem", "meet", "week", "deep", "keep"]),
    dict(phase=3, ls_set=None, group="igh", after=38, source="ls2007:p.102", target="igh",
         words=["high", "sigh", "light", "might", "night", "right", "sight", "fight", "tight",
                "tonight"]),
    dict(phase=3, ls_set=None, group="oa", after=39, source="ls2007:p.102", target="oa",
         words=["coat", "load", "goat", "loaf", "road", "soap", "oak", "toad", "foal", "boatman"]),
    dict(phase=3, ls_set=None, group="oo (long)", after=40, source="ls2007:p.102", target="oo_long",
         words=["too", "zoo", "boot", "hoof", "zoom", "cool", "food", "root", "moon", "rooftop"]),
    dict(phase=3, ls_set=None, group="oo (short)", after=41, source="ls2007:p.102", target="oo_short",
         words=["look", "foot", "cook", "good", "book", "took", "wood", "wool", "hook", "hood"]),
    dict(phase=3, ls_set=None, group="ar", after=42, source="ls2007:p.102", target="ar",
         words=["bar", "car", "bark", "card", "cart", "hard", "jar", "park", "market", "farmyard"]),
    dict(phase=3, ls_set=None, group="or", after=43, source="ls2007:p.102", target="or",
         words=["for", "fork", "cord", "cork", "sort", "born", "fort", "torn", "cornet", "worn"]),
    dict(phase=3, ls_set=None, group="ur", after=44, source="ls2007:p.102", target="ur",
         words=["fur", "burn", "urn", "burp", "curl", "hurt", "surf", "turn", "turnip", "curds"]),
    dict(phase=3, ls_set=None, group="ow", after=45, source="ls2007:p.102", target="ow",
         words=["now", "down", "owl", "cow", "how", "bow", "pow", "row", "town", "towel"]),
    dict(phase=3, ls_set=None, group="oi", after=46, source="ls2007:p.102", target="oi",
         words=["oil", "boil", "coin", "coil", "join", "soil", "toil", "quoit", "poison", "tinfoil"]),
    dict(phase=3, ls_set=None, group="ear", after=47, source="ls2007:p.102", target="ear",
         words=["ear", "dear", "fear", "hear", "gear", "near", "tear", "year", "rear", "beard"]),
    dict(phase=3, ls_set=None, group="air", after=48, source="ls2007:p.102", target="air",
         words=["air", "fair", "hair", "lair", "pair", "cairn"]),
    dict(phase=3, ls_set=None, group="ure", after=49, source="ls2007:p.102", target="ure",
         words=["sure", "lure", "assure", "insure", "pure", "cure", "secure", "manure", "mature"]),
    dict(phase=3, ls_set=None, group="er", after=50, source="ls2007:p.102", target="er",
         words=["hammer", "letter", "rocker", "ladder", "supper", "dinner", "boxer", "better",
                "summer", "banner"]),
    dict(phase=3, ls_set=None, group="two Phase Three graphemes", after=50, source="ls2007:p.103",
         target=None,
         words=["cheep", "tooth", "chair", "sharp", "torch", "looking", "sheet", "harsh", "waiter",
                "poach", "orchard", "powder", "thing", "short", "arch", "shoal", "north",
                "lightning", "thorn", "church", "chain", "shook", "farmer", "porch", "teeth",
                "singer", "faith", "shark", "shorter", "thicker", "coach", "shear", "sheep",
                "march", "longer", "booth"]),
    # ---------------- Phase 4, p.126-127 ----------------
    dict(phase=4, ls_set=None, group="CVCC, sets 1-7 letters", after=50, source="ls2007:p.126",
         target=None,
         words=["went", "it's", "help", "just", "tent", "belt", "hump", "band", "dent", "felt",
                "gulp", "lamp", "wind", "land", "nest", "sink", "link", "hunt", "best", "tilt",
                "lift", "lost", "tuft", "damp", "bust", "camp", "gift", "kept", "tusk", "limp",
                "soft", "pond", "husk", "cost", "bank", "bunk", "fond", "gust", "hand", "next",
                "milk", "golf", "jump", "fact", "melt", "ask", "fast", "last", "daft", "task"]),
    dict(phase=4, ls_set=None, group="CVCC, Phase Three graphemes", after=50, source="ls2007:p.126",
         target=None,
         words=["champ", "chest", "tenth", "theft", "welsh", "chimp", "bench", "sixth", "punch",
                "chunk", "thank", "shift", "shelf", "joint", "boost", "thump", "paint", "roast",
                "toast", "beast", "think", "burnt"]),
    dict(phase=4, ls_set=None, group="CVCC, polysyllabic", after=50, source="ls2007:p.126",
         target=None,
         words=["children", "helpdesk", "sandpit", "windmill", "softest", "pondweed", "desktop",
                "helper", "handstand", "melting", "seventh", "shampoo", "chester", "giftbox",
                "shelter", "lunchbox", "sandwich", "shelving", "manchester", "chimpanzee",
                "champion", "thundering"]),
    dict(phase=4, ls_set=None, group="CCV/CCVC, sets 1-7 letters", after=50, source="ls2007:p.127",
         target=None,
         words=["from", "stop", "spot", "frog", "step", "plan", "speck", "trip", "grab", "track",
                "spin", "flag", "grip", "glad", "twin", "sniff", "plum", "gran", "swim", "clap",
                "drop", "glass", "grass", "brass"]),
    dict(phase=4, ls_set=None, group="CCV/CCVC, Phase Three graphemes", after=50,
         source="ls2007:p.127", target=None,
         words=["green", "fresh", "tree", "spear", "smell", "spoil", "train", "spoon", "sport",
                "thrush", "trash", "start", "flair", "trail", "cream", "clown", "star", "creep",
                "brown", "stair", "spark", "bring", "crash", "bleed", "clear", "swing", "droop",
                "float", "smart", "groan", "brush", "growl", "scoop", "frown", "speech", "smear",
                "thrill"]),
    dict(phase=4, ls_set=None, group="CCVC, polysyllabic", after=50, source="ls2007:p.127",
         target=None,
         words=["treetop", "starlight", "floating", "freshness"]),
    dict(phase=4, ls_set=None, group="CCVCC/CCCVC, sets 1-7 letters", after=50,
         source="ls2007:p.127", target=None,
         words=["stand", "crisp", "trend", "trust", "spend", "glint", "twist", "brand", "frost",
                "cramp", "plump", "stamp", "blend", "stunt", "crust", "tramp", "grunt", "crept",
                "drift", "slept", "skunk", "graft", "grant", "blast", "grasp", "slant"]),
    dict(phase=4, ls_set=None, group="CCVCC/CCCVC, Phase Three graphemes", after=50,
         source="ls2007:p.127", target=None,
         words=["crunch", "drench", "trench", "grinch", "shrink", "thrust", "spring", "strap",
                "string", "scrap", "street", "scrunch", "blink", "drank", "blank", "trunk"]),
    dict(phase=4, ls_set=None, group="CCVCC, polysyllabic", after=50, source="ls2007:p.127",
         target=None,
         words=["driftwood", "twisting", "printer"]),
    # ---------------- Phase 5, p.151-152 ----------------
    dict(phase=5, ls_set=None, group="ay", after=51, source="ls2007:p.151", target="ay",
         words=["day", "play", "may", "say", "stray", "clay", "spray", "tray", "crayon", "delay"]),
    dict(phase=5, ls_set=None, group="ou", after=52, source="ls2007:p.151", target="ou",
         words=["out", "about", "cloud", "scout", "found", "proud", "sprout", "sound", "loudest",
                "mountain"]),
    dict(phase=5, ls_set=None, group="ie", after=53, source="ls2007:p.151", target="ie",
         words=["pie", "lie", "tie", "die", "cried", "tried", "spied", "fried", "replied",
                "denied"]),
    dict(phase=5, ls_set=None, group="ea", after=54, source="ls2007:p.151", target="ea",
         words=["sea", "seat", "bead", "read", "meat", "treat", "heap", "least", "steamy",
                "repeat"]),
    dict(phase=5, ls_set=None, group="oy", after=55, source="ls2007:p.151", target="oy",
         words=["boy", "toy", "joy", "oyster", "roy", "destroy", "floyd", "enjoy", "royal",
                "annoying"]),
    dict(phase=5, ls_set=None, group="ir", after=56, source="ls2007:p.151", target="ir",
         words=["girl", "sir", "bird", "shirt", "skirt", "birth", "third", "first", "thirteen",
                "thirsty"]),
    dict(phase=5, ls_set=None, group="ue (as in clue)", after=57, source="ls2007:p.151",
         target="ue_oo",
         words=["clue", "blue", "glue", "true", "sue", "prue", "rue", "flue"]),
    dict(phase=5, ls_set=None, group="ue (as in cue)", after=58, source="ls2007:p.151",
         target="ue_yoo",
         words=["cue", "due", "hue", "venue", "value", "pursue", "queue", "statue", "issue",
                "tissue", "rescue", "argue"]),
    dict(phase=5, ls_set=None, group="aw", after=59, source="ls2007:p.151", target="aw",
         words=["saw", "paw", "raw", "claw", "jaw", "lawn", "yawn", "law", "shawl", "drawer"]),
    dict(phase=5, ls_set=None, group="wh", after=60, source="ls2007:p.151", target="wh",
         words=["when", "which", "where", "why", "whistle", "whenever", "wheel", "whisper",
                "white"]),
    dict(phase=5, ls_set=None, group="ph", after=61, source="ls2007:p.151", target="ph",
         words=["philip", "philippa", "phonics", "sphinx", "christopher", "dolphin", "prophet",
                "phantom", "elephant", "alphabet"]),
    dict(phase=5, ls_set=None, group="ew (as in blew)", after=62, source="ls2007:p.151",
         target="ew_oo",
         words=["blew", "chew", "grew", "drew", "screw", "crew", "brew", "flew", "threw",
                "andrew"]),
    dict(phase=5, ls_set=None, group="ew (as in stew)", after=63, source="ls2007:p.151",
         target="ew_yoo",
         words=["stew", "few", "new", "dew", "pew", "knew", "mildew", "nephew", "renew",
                "matthew"]),
    dict(phase=5, ls_set=None, group="oe", after=64, source="ls2007:p.151", target="oe",
         words=["toe", "hoe", "doe", "foe", "woe", "joe", "goes", "tomatoes", "potatoes",
                "heroes"]),
    dict(phase=5, ls_set=None, group="au", after=65, source="ls2007:p.151", target="au",
         words=["paul", "haul", "daub", "launch", "haunted", "saul", "august", "jaunty", "author",
                "automatic"]),
    dict(phase=5, ls_set=None, group="ey (as in money)", after=66, source="ls2007:p.151",
         target="ey_ee",
         words=["money", "honey", "donkey", "cockney", "jockey", "turkey", "chimney", "valley",
                "trolley", "monkey"]),
    dict(phase=5, ls_set=None, group="a-e", after=67, source="ls2007:p.152", target="a-e",
         words=["came", "made", "make", "take", "game", "race", "same", "snake", "amaze",
                "escape"]),
    dict(phase=5, ls_set=None, group="e-e", after=68, source="ls2007:p.152", target="e-e",
         words=["these", "pete", "eve", "steve", "even", "theme", "gene", "scene", "complete",
                "extreme"]),
    dict(phase=5, ls_set=None, group="i-e", after=69, source="ls2007:p.152", target="i-e",
         words=["like", "time", "pine", "ripe", "shine", "slide", "prize", "nice", "invite",
                "inside"]),
    dict(phase=5, ls_set=None, group="o-e", after=70, source="ls2007:p.152", target="o-e",
         words=["bone", "pole", "home", "alone", "those", "stone", "woke", "note", "explode",
                "envelope"]),
    dict(phase=5, ls_set=None, group="u-e (as in rule)", after=71, source="ls2007:p.152",
         target="u-e_oo",
         words=["june", "flute", "prune", "rude", "rule"]),
    dict(phase=5, ls_set=None, group="u-e (as in cube)", after=72, source="ls2007:p.152",
         target="u-e_yoo",
         words=["huge", "cube", "tube", "use", "computer"]),
]

# --------------------------------------------------------------------------
# Captions and sentences, transcribed verbatim.
# --------------------------------------------------------------------------

CAPTIONS = [
    # p.71 -- Phase 2
    dict(phase=2, after=12, source="ls2007:p.71", kind="caption",
         group="Captions with sets 1-3 words",
         items=["pat a dog", "a cat in a hat", "a sad man", "a pin on a map", "pots and pans",
                "dad and nan", "a nap in a cot", "a kid in a cap", "a tin can", "cats and dogs"]),
    dict(phase=2, after=16, source="ls2007:p.71", kind="caption",
         group="Captions with sets 1-4 words + to, the",
         items=["a red rug", "get to the top", "socks on a mat", "a cap on a peg",
                "a run in the sun", "rats on a sack", "a pup in the mud", "run to the den",
                "mugs and cups", "an egg in an egg cup"]),
    dict(phase=2, after=23, source="ls2007:p.71", kind="caption",
         group="Captions, instructions and signs with sets 1-5 words + to, the, no, go",
         items=["a hug and a kiss", "on top of the rock", "a bag of nuts", "to huff and puff",
                "go to the log hut", "a hot hob", "sit back to back", "a duck and a hen",
                "a cat on a bed", "to the top of the hill", "get off the bus", "no lid on the pan",
                "pack a pen in a bag", "a doll in a cot", "a cat and a big fat rat"]),
    # p.100 -- Phase 3 yes/no questions
    dict(phase=3, after=27, source="ls2007:p.100", kind="question",
         group="Yes/no questions with words containing sets 1-6 GPCs",
         items=["Is the sun wet?", "Can wax get hot?", "Has a fox got six legs?",
                "Can a vet fix a jet?", "Will a pen fit in a box?", "Can men jog to get fit?",
                "Has a pot of jam got a lid?", "Can a taxi hop?", "Can a van go up a hill?",
                "Has a cat got a web?"]),
    dict(phase=3, after=31, source="ls2007:p.100", kind="question",
         group="Yes/no questions with words containing sets 1-7 GPCs",
         items=["Can a duck quack?", "Is a zebra a pet?", "Can dogs yap?", "Can a fox get wet?",
                "Will a box fit in a van?", "Can a rabbit yell at a man?", "Can a hen peck?",
                "Is a lemon red?", "Is a robin as big as a jet?", "Can a web buzz?"]),
    # p.101 -- Phase 3 sentences
    # after=35, not 31: the heading says these sentences use 'we', and the L&S
    # timetable (p.76) teaches 'we' in week 8, with the consonant digraphs.
    dict(phase=3, after=35, source="ls2007:p.101", kind="sentence",
         group="Sentences using words containing sets 1-7 GPCs and he, we and she",
         items=["She will fill the bucket at the well.",
                "If the dog has a bad leg, the vet can fix it.",
                "Will Azam and Liz win the quiz? Yes!",
                "He did up the zip on Zinat's jacket.",
                "The fox and vixen had cubs in a den.",
                "We can get the big bed into the van."]),
    dict(phase=3, after=35, source="ls2007:p.101", kind="sentence",
         group="Sentences with sets 1-7 letters plus the four consonant digraphs and some tricky words",
         items=["I am in such a rush to get to the shops.",
                "A man is rich if he has lots of cash.",
                "Natasha sang a song to me.",
                "The van will chug up the long hill.",
                "Sasha had a quick chat with Kath and me.",
                "A moth can be fat, but its wings are thin.",
                "The ship hit the rocks with a thud.",
                "Lots of shops sell chicken as well as fish and chips.",
                "Josh had a shock as he got a bash on the chin."]),
    # p.103 -- Phase 3 captions and sentences
    dict(phase=3, after=50, source="ls2007:p.103", kind="caption", group="Captions",
         items=["tools in the shed", "ships in port", "boats on the river",
                "fish and chips on a dish", "a goat and a cow", "sixteen trees",
                "looking at books", "the light of a torch", "digging in the soil",
                "goats in a farmyard"]),
    dict(phase=3, after=50, source="ls2007:p.103", kind="sentence", group="Sentences",
         items=["Mark and Carl got wet in the rain.",
                "Jill has fair hair but Jack has dark hair.",
                "I can hear an owl hoot at night.",
                "Bow down to the king and queen.",
                "I can see a pair of boots on the mat.",
                "The farmer gets up at six in the morning.",
                "Jim has seven silver coins.",
                "Nan is sitting in the rocking-chair.",
                "Gurdeep had a chat with his dad.",
                "It has been hot this year."]),
    # p.128 -- Phase 4 sentences and questions
    dict(phase=4, after=50, source="ls2007:p.128", kind="sentence", group="Sentences",
         items=["Fred and Brett spent a week in Spain.",
                "I kept bumping into things in the dark.",
                "Milk is good for children's teeth.",
                "The clown did tricks with a chimpanzee.",
                "The frog jumps in the pond and swims off.",
                "I must not tramp on the flowers.",
                "A crab crept into a crack in the rock.",
                "A drip from the tap drops in the sink.",
                "I can hear twigs snapping in the wind.",
                "It is fun to camp in a tent."]),
    dict(phase=4, after=50, source="ls2007:p.128", kind="question", group="Yes/no questions",
         items=["Can a clock get cross?", "Can crabs clap hands?", "Are you fond of plums?",
                "Did a shark ever jump up a tree?", "Can frogs swim in ponds?",
                "Is the moon green?", "Can you bang on a big drum?",
                "Have you ever slept in a tent?", "Are all children good at sport?",
                "Have you seen a trail left by a snail?",
                "Are you afraid of thunderstorms?", "Can a spoon grab a fork?",
                "Do chimps come from Mars?", "Can letters have stamps stuck on them?",
                "Do trains run on tracks?", "Will a truck go up steep stairs?",
                "Do some dogs have black spots?", "Are you glad when you have a pain?",
                "Can we see the stars on a clear night?"]),
]

# Five short connected texts, p.103 -- "Sentences for the end of Phase Three".
TEXTS = [
    dict(title="on the farm", phase=3, after=50, source="ls2007:p.103",
         lines=["I will soon visit my nan at her farm.",
                "She will let me feed the hens and chickens.",
                "They peck up corn in the farmyard.",
                "She has goats and cows as well as hens.",
                "She gets the hens into a shed at night - foxes might get them."]),
    dict(title="in town", phase=3, after=50, source="ls2007:p.103",
         lines=["You and I can meet on the corner.",
                "We can get the bus to the fish and chip shop.",
                "Janaki and her sister may join us.",
                "They can get fish and chips, too.",
                "Then we can all run to the park."]),
    dict(title="in a wigwam", phase=3, after=50, source="ls2007:p.103",
         lines=["Kevin has a wigwam in the garden.",
                "Alex, Jon and Jeevan visit him.",
                "Kevin's dad cooks chicken for them on hot coals.",
                "Having food in the wigwam is fun.",
                "Then they sing songs."]),
    dict(title="at the river", phase=3, after=50, source="ls2007:p.103",
         lines=["Max and Vikram sail a wooden boat.",
                "Jeff chucks bits of bun in the river for the ducks.",
                "Yasmin sits on a rock and looks for fish.",
                "Tanya and Yasha see an eel.",
                "Shep the dog sits down in the mud and gets in a mess."]),
    dict(title="in the woods", phase=3, after=50, source="ls2007:p.103",
         lines=["Chip the dog runs to the woods.",
                "He is looking for rabbits but sees a fox.",
                "The fox sees him and rushes off to its den.",
                "Chip dashes after it but cannot see it.",
                "He feels sad and runs back to his kennel."]),
]

# --------------------------------------------------------------------------
# Tricky words (read).  after = the GPC order after which L&S teaches them.
# --------------------------------------------------------------------------

TRICKY = [
    # Phase 2 (p.50)
    ("to", 2, 16, "ls2007:p.50", ["t", "o_oo"]),
    ("the", 2, 16, "ls2007:p.50", ["th_voiced", "e_ee"]),
    ("no", 2, 23, "ls2007:p.50", ["n", "o_oh"]),
    ("go", 2, 23, "ls2007:p.50", ["g", "o_oh"]),
    ("i", 2, 23, "ls2007:p.50", ["i_eye"]),
    # Phase 3 (p.76-77)
    ("he", 3, 31, "ls2007:p.76", ["h", "e_ee"]),
    ("she", 3, 31, "ls2007:p.76", ["sh", "e_ee"]),
    ("we", 3, 35, "ls2007:p.76", ["w", "e_ee"]),
    ("me", 3, 35, "ls2007:p.76", ["m", "e_ee"]),
    ("be", 3, 35, "ls2007:p.76", ["b", "e_ee"]),
    ("was", 3, 39, "ls2007:p.76", ["w", "a_o", "s_z"]),
    ("my", 3, 46, "ls2007:p.77", ["m", "y_eye"]),
    ("you", 3, 46, "ls2007:p.77", ["y", "ou_oo"]),
    ("her", 3, 50, "ls2007:p.77", ["h", "er_ur"]),
    ("they", 3, 50, "ls2007:p.77", ["th_voiced", "ey_ay"]),
    ("all", 3, 50, "ls2007:p.77", ["a_or", "ll"]),
    ("are", 3, 50, "ls2007:p.77", ["ar", "e_silent"]),
    # Phase 4 (p.114, p.125)
    ("said", 4, None, "ls2007:p.114", ["s", "ai_e", "d"]),
    ("so", 4, None, "ls2007:p.114", ["s", "o_oh"]),
    ("do", 4, None, "ls2007:p.114", ["d", "o_oo"]),
    ("have", 4, None, "ls2007:p.114", ["h", "a", "v", "e_silent"]),
    ("like", 4, None, "ls2007:p.114", ["l", "i-e", "k"]),
    ("some", 4, None, "ls2007:p.114", ["s", "o_u", "m", "e_silent"]),
    ("come", 4, None, "ls2007:p.114", ["c", "o_u", "m", "e_silent"]),
    ("were", 4, None, "ls2007:p.114", ["w", "ere_er"]),
    ("there", 4, None, "ls2007:p.114", ["th_voiced", "ere_er"]),
    ("little", 4, None, "ls2007:p.114", ["l", "i", "tt", "le"]),
    ("one", 4, None, "ls2007:p.114", ["o_u", "n", "e_silent"]),
    ("when", 4, None, "ls2007:p.114", ["wh", "e", "n"]),
    ("out", 4, None, "ls2007:p.114", ["ou", "t"]),
    ("what", 4, None, "ls2007:p.114", ["wh", "a_o", "t"]),
    # Phase 5 (p.132-133)
    ("oh", 5, None, "ls2007:p.132", ["o_oh", "silent"]),
    ("their", 5, None, "ls2007:p.132", ["th_voiced", "ei", "r"]),
    ("people", 5, None, "ls2007:p.132", ["p", "eo", "p", "le"]),
    ("mr", 5, None, "ls2007:p.132", ["m", "silent", "r"]),
    ("mrs", 5, None, "ls2007:p.132", ["m", "silent", "r", "s"]),
    ("looked", 5, None, "ls2007:p.132", ["l", "oo_short", "k", "ed_t"]),
    ("called", 5, None, "ls2007:p.132", ["c", "a_or", "ll", "ed_d"]),
    ("asked", 5, None, "ls2007:p.132", ["a", "s", "k", "ed_t"]),
    ("water", 5, None, "ls2007:p.133", ["w", "a_or", "t", "er"]),
    ("where", 5, None, "ls2007:p.133", ["wh", "ere_er"]),
    ("who", 5, None, "ls2007:p.133", ["wh", "o_oo"]),
    ("again", 5, None, "ls2007:p.133", ["a", "g", "ai", "n"]),
    ("thought", 5, None, "ls2007:p.133", ["th", "ough"]),
    ("through", 5, None, "ls2007:p.133", ["th", "r", "ough"]),
    ("work", 5, None, "ls2007:p.133", ["w", "or_er", "k"]),
    ("mouse", 5, None, "ls2007:p.133", ["m", "ou", "s", "e_silent"]),
    ("many", 5, None, "ls2007:p.133", ["m", "a", "n", "y_ee"]),
    ("laughed", 5, None, "ls2007:p.133", ["l", "augh", "ed_t"]),
    ("because", 5, None, "ls2007:p.133", ["b", "e_ee", "c", "au", "s_z", "e_silent"]),
    ("different", 5, None, "ls2007:p.133", ["d", "i", "ff", "er", "e", "n", "t"]),
    ("any", 5, None, "ls2007:p.133", ["a", "n", "y_ee"]),
    ("eyes", 5, None, "ls2007:p.133", ["ei", "y_eye", "e_silent", "s_z"]),
    ("friends", 5, None, "ls2007:p.133", ["f", "r", "silent", "e", "n", "d", "s_z"]),
    ("once", 5, None, "ls2007:p.133", ["o_u", "n", "c_s", "e_silent"]),
    ("please", 5, None, "ls2007:p.133", ["p", "l", "ea", "s_z", "e_silent"]),
]

# High-frequency words L&S says are *decodable* by the end of each phase.
DECODABLE_HFW = {
    2: ["is", "it", "in", "at", "and"],
    3: ["will", "with", "that", "this", "then", "them", "see", "for", "now", "down", "look",
        "too"],
    4: ["went", "it's", "from", "children", "just", "help"],
}
