#!/usr/bin/bash
# Install the real kidnix activity shell (shell/ in the repo) into the image
# and wire the session units that run it.
#
# WHY A PLAIN COPY AND NOT pip:
# `kidnix-shell` is pure Python with **zero** runtime dependencies from PyPI
# (shell/pyproject.toml: PyGObject, GTK4, libadwaita and speechd all come from
# RPMs). Its build backend is hatchling, so `pip install` would need
# python3-pip *and* python3-hatchling installed into the image and then removed
# again -- two extra packages, a dnf remove that can cascade, and a build that
# reaches the network -- to produce a tree that is byte-for-byte the same as
# `cp -a kidnix_shell $purelib/`. The copy is the least fragile option, and
# every claim it makes is asserted at the bottom of this file.
#
# The one thing pip would give us for free is .dist-info metadata, so we write
# the two files of it that anything actually reads.
set -euo pipefail

log() { printf '  -- %s\n' "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

SRC=/tmp/shell
[[ -d "${SRC}/kidnix_shell" ]] || die "${SRC}/kidnix_shell is missing -- the Containerfile must COPY shell/ /tmp/shell/"

VERSION="$(sed -n 's/^__version__ = "\(.*\)"$/\1/p' "${SRC}/kidnix_shell/__init__.py")"
[[ -n "${VERSION}" ]] || die "could not read __version__ from ${SRC}/kidnix_shell/__init__.py"

# -----------------------------------------------------------------------------
# 1. The Python package
# -----------------------------------------------------------------------------

# sysconfig's default purelib is /usr/local/..., which on an ostree system is a
# symlink into /var and therefore NOT part of the image. Ask for the /usr
# scheme explicitly.
PURELIB="$(python3 -c 'import sysconfig; print(sysconfig.get_path("purelib", "posix_prefix", vars={"base": "/usr", "platbase": "/usr"}))')"
[[ "${PURELIB}" == /usr/lib/* ]] || die "refusing to install outside /usr: ${PURELIB}"
log "site-packages: ${PURELIB}"

# A developer checkout can carry __pycache__ compiled by a different Python.
# Those would be *imported* by the image's Python 3.14 if their magic happened
# to match, so they never get to travel. (.containerignore drops them too; this
# is the belt to that pair of braces.)
find "${SRC}" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true
find "${SRC}" -name '*.py[co]' -delete 2>/dev/null || true

install -d "${PURELIB}"
rm -rf "${PURELIB:?}/kidnix_shell"
cp -a "${SRC}/kidnix_shell" "${PURELIB}/kidnix_shell"

# The metadata a wheel install would have left behind. METADATA is what
# importlib.metadata.version("kidnix-shell") reads; INSTALLER is what tells a
# future maintainer that rpm/dnf does not own these files.
DISTINFO="${PURELIB}/kidnix_shell-${VERSION}.dist-info"
rm -rf "${DISTINFO}"
install -d "${DISTINFO}"
cat >"${DISTINFO}/METADATA" <<EOF
Metadata-Version: 2.1
Name: kidnix-shell
Version: ${VERSION}
Summary: kidnix activity shell -- the full-screen surface a child sees
License: Apache-2.0
Requires-Python: >=3.11
EOF
printf 'kidnix-image-build\n' >"${DISTINFO}/INSTALLER"
printf 'kidnix_shell\n' >"${DISTINFO}/top_level.txt"

# /usr is read-only at runtime, so an image without .pyc files re-parses the
# whole shell on every start and can never cache the result. `unchecked-hash`
# invalidation keeps the .pyc valid regardless of mtimes, which is what an
# ostree commit needs.
python3 -m compileall -q -f --invalidation-mode unchecked-hash "${PURELIB}/kidnix_shell" \
    || die "byte-compiling kidnix_shell failed"

# -----------------------------------------------------------------------------
# 2. The entry point
# -----------------------------------------------------------------------------

# shell/pyproject.toml declares `kidnix-shell = "kidnix_shell.cli:main"`, but
# /usr/bin/kidnix-shell is already taken by the *session wrapper* GDM execs
# (system_files/usr/bin/kidnix-shell -> gnome-session --session=kidnix), so the
# application itself gets an unambiguous name. kidnix-shell.service runs this.
cat >/usr/bin/kidnix-shell-app <<'EOF'
#!/usr/bin/python3
# The `kidnix-shell` console script from shell/pyproject.toml, installed under
# a name that does not collide with the session wrapper in /usr/bin/kidnix-shell.
# Generated by build_files/60-shell.sh -- do not edit in the image.
import sys

from kidnix_shell.cli import main

if __name__ == "__main__":
    sys.exit(main())
EOF
chmod 0755 /usr/bin/kidnix-shell-app

# -----------------------------------------------------------------------------
# 3. Assert the whole thing actually works
# -----------------------------------------------------------------------------

log "verifying the install"

# Import from a directory that is definitely not the source tree, so a stray
# CWD cannot make this pass by accident.
( cd / && python3 -c 'import kidnix_shell, sys; sys.exit(0 if kidnix_shell.__file__.startswith("/usr/lib/") else 1)' ) \
    || die "kidnix_shell does not import from /usr/lib"

( cd / && python3 -m kidnix_shell --version >/dev/null ) || die "python3 -m kidnix_shell --version failed"
( cd / && /usr/bin/kidnix-shell-app --version >/dev/null ) || die "/usr/bin/kidnix-shell-app --version failed"

# The GTK side has to import too, or the session comes up to a black screen and
# a traceback in the journal that nobody sees until a child is sitting there.
# There is no display in a build container, so import the module without
# realising a window.
( cd / && python3 -c '
import gi
gi.require_version("Gtk", "4.0")
gi.require_version("Adw", "1")
from gi.repository import Adw, Gtk  # noqa: F401
import kidnix_shell.app  # noqa: F401
' ) || die "the shell cannot import GTK4/libadwaita (python3-gobject, gtk4, libadwaita)"

# Read-aloud. python3-speechd is the preferred backend; spd-say is the fallback
# (spec section 3). Missing both is a degraded-but-shippable state for a dev
# host and an unacceptable one for the image, so require the good path here.
( cd / && python3 -c 'import speechd' ) || die "python3-speechd is missing (read-aloud backend)"
command -v spd-say >/dev/null || die "spd-say is missing (read-aloud fallback)"

# Every manifest we ship must load, or Home comes up empty for a child.
( cd / && /usr/bin/kidnix-shell-app --validate-manifests /usr/share/kidnix/activities ) \
    || die "shipped activity manifests do not validate"

# The theme and the bundled fallback icons have to have travelled with the
# package; they are loaded by path, not by import.
for asset in "${PURELIB}/kidnix_shell/theme.css" \
             "${PURELIB}/kidnix_shell/data/icons/kidnix-make.svg"; do
    [[ -f "${asset}" ]] || die "packaged asset missing: ${asset}"
done

# -----------------------------------------------------------------------------
# 4. Session wiring
# -----------------------------------------------------------------------------
#
# The units and the .session file are shipped in system_files/; all that is
# left is to prove they are consistent with each other, because every one of
# these mistakes produces the same symptom (GDM bounces the child back to a
# greeter) and none of them is visible until boot.

SESSION_FILE=/usr/share/gnome-session/sessions/kidnix.session
DROPIN=/usr/lib/systemd/user/gnome-session@kidnix.target.d/session.conf
UNIT=/usr/lib/systemd/user/kidnix-shell.service

[[ -f "${SESSION_FILE}" ]] || die "${SESSION_FILE} is missing"
[[ -f "${DROPIN}" ]]       || die "${DROPIN} is missing"
[[ -f "${UNIT}" ]]         || die "${UNIT} is missing"

# gnome-session --session=kidnix resolves to gnome-session@kidnix.target, so
# the .session basename and the drop-in directory name must agree.
grep -q '^Name=kidnix$' "${SESSION_FILE}" || die "${SESSION_FILE} has no Name=kidnix"
grep -q '^exec /usr/bin/gnome-session --session=kidnix$' /usr/bin/kidnix-shell \
    || die "/usr/bin/kidnix-shell does not exec gnome-session --session=kidnix"

grep -q '^Requires=org.gnome.Kiosk.target$' "${DROPIN}" || die "${DROPIN} does not require the kiosk compositor"
grep -q '^Wants=kidnix-shell.service$'      "${DROPIN}" || die "${DROPIN} does not pull in kidnix-shell.service"
grep -q '^Restart=always$'                  "${UNIT}"   || die "${UNIT} is not Restart=always"
grep -q '^ExecStart=/usr/bin/kidnix-shell-app$' "${UNIT}" || die "${UNIT} does not start the shell"
# Without this the autospawned speech-dispatcher joins the shell's cgroup and
# ignores SIGTERM, turning every restart into an 11 s stall. Measured; see
# docs/spikes/session-integration.md.
grep -q '^Wants=speech-dispatcher.socket$' "${UNIT}" || die "${UNIT} does not socket-activate speech-dispatcher"
[[ -f /usr/lib/systemd/user/speech-dispatcher.socket ]] || die "speech-dispatcher ships no user socket unit"
grep -q 'ListenStream=%t/speech-dispatcher/speechd.sock' /usr/lib/systemd/user/speech-dispatcher.socket \
    || die "speech-dispatcher.socket no longer listens where python3-speechd looks"

# The units gnome-kiosk and gnome-session contribute must exist, or the target
# above resolves to nothing at all.
for unit in /usr/lib/systemd/user/org.gnome.Kiosk.target \
            /usr/lib/systemd/user/org.gnome.Kiosk@wayland.service \
            /usr/lib/systemd/user/gnome-session@.target \
            /usr/lib/systemd/user/gnome-session-initialized.target; do
    [[ -f "${unit}" ]] || die "expected unit missing from the image: ${unit}"
done

# systemd's own opinion of the unit files, which catches a typo'd directive
# that grep cannot. `verify` also resolves dependencies, and in a build
# container the units it chases (gnome-session.target and friends) are present
# but their own dependencies are not, so only complaints about OUR file are
# treated as fatal.
if command -v systemd-analyze >/dev/null 2>&1; then
    # `--user verify` needs somewhere to pretend a runtime directory is; without
    # XDG_RUNTIME_DIR it bails with "Failed to initialize manager" and verifies
    # nothing at all, silently.
    mkdir -p /tmp/kidnix-verify-runtime
    verify_out="$(XDG_RUNTIME_DIR=/tmp/kidnix-verify-runtime \
        systemd-analyze --user verify --recursive-errors=no "${UNIT}" 2>&1 || true)"
    rmdir /tmp/kidnix-verify-runtime 2>/dev/null || true
    if grep -q 'kidnix-shell.service' <<<"${verify_out}"; then
        printf '%s\n' "${verify_out}" >&2
        die "systemd-analyze rejected ${UNIT}"
    fi
    [[ -z "${verify_out}" ]] || log "systemd-analyze notes (not about our unit): ${verify_out//$'\n'/ | }"
fi

# The session policy the shell reads at start.
[[ -f /etc/kidnix/session.toml ]] || die "/etc/kidnix/session.toml is missing"
( cd / && python3 -c '
import sys, tomllib
with open("/etc/kidnix/session.toml", "rb") as fh:
    data = tomllib.load(fh)
required = {"length_minutes", "daily_budget_minutes", "ending_offer_minutes",
            "put_away_minutes", "bedtime_start", "bedtime_end"}
missing = required - set(data)
if missing:
    sys.exit("session.toml is missing keys: " + ", ".join(sorted(missing)))
' ) || die "/etc/kidnix/session.toml is not valid"

# The activity manifest directory the shell looks in
# (kidnix_shell.activities.SYSTEM_ACTIVITY_DIR).
[[ -d /usr/share/kidnix/activities ]] || die "/usr/share/kidnix/activities is missing"

rm -rf "${SRC}"

log "kidnix-shell ${VERSION} installed into ${PURELIB}"
